$engine: 3
$onesync: on
name: Server name goes HERE
author: DonStylz74
description: FiveM RP framework, ESX Legacy, Contains Jobs, Housing, Garages & more!

tasks:
  ## Download default CFX resources
  - action: download_github
    src: https://github.com/citizenfx/cfx-server-data
    ref: master
    subpath: resources
    dest: ./resources/[cfx-default]

  ## Download and prepare server.cfg / loadingscreen / database
  - action: download_github
    src: https://github.com/DonStylz74/esx-recipe-slrp
    ref: main
    dest: ./recipe

  - action: move_path
    src: ./recipe/server.cfg
    dest: ./server.cfg

  - action: move_path
    src: ./recipe/ox.cfg
    dest: ./ox.cfg

  - action: move_path
    src: ./recipe/esxLogo.png
    dest: ./esxLogo.png

  ## Download basic resources and ESX dependencies

  - action: connect_database

  - action: waste_time # prevent github throttling
    seconds: 10


  - action: download_github
    src: https://github.com/esx-framework/esx-core
    ref: main
    dest: ./tmp/core

  - action: download_github
    src: https://github.com/esx-framework/ESX-Legacy-Addons/
    ref: main
    dest: ./tmp/addons

  - action: move_path
    src: ./tmp/core/[core]
    dest: ./resources/[core]
    overwrite: true

  - action: move_path
    src: ./tmp/addons/[esx_addons]
    dest: ./resources/[esx_addons]
    overwrite: true

  - action: waste_time
    seconds: 10

## --- '###################################' --- ##
## --- '### SERVER BASE CLEANUP PROCESS ###' --- ##
## --- '###################################' --- ##

  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat

  - action: remove_path
    path: ./resources/[cfx-default]/[gameplay]/chat-theme-gtao

  - action: remove_path
    path: ./resources/[core]/esx_chat_theme

  - action: remove_path
    path: ./resources/[core]/esx_skin

  - action: remove_path
    path: ./resources/[core]/skinchanger

  - action: remove_path
    path: ./resources/[core]/esx_identity

  - action: remove_path
    path: ./resources/[core]/esx_multicharacter

  - action: remove_path
    path: ./resources/[core]/esx_loadingscreen

  - action: remove_path
    path: ./resources/[esx_addons]/esx_addoninventory

  - action: remove_path
    path: ./resources/[esx_addons]/esx_animations

  - action: remove_path
    path: ./resources/[esx_addons]/esx_banking

  - action: remove_path
    path: ./resources/[esx_addons]/esx_billing

  - action: remove_path
    path: ./resources/[esx_addons]/esx_barbershop

  - action: remove_path
    path: ./resources/[esx_addons]/esx_accessories

  - action: remove_path
    path: ./resources/[esx_addons]/esx_cruisecontrol

  - action: remove_path
    path: ./resources/[esx_addons]/esx_vehicleshop

  - action: remove_path
    path: ./resources/[esx_addons]/esx_boat

  - action: remove_path
    path: ./resources/[esx_addons]/esx_clotheshop

  - action: remove_path
    path: ./resources/[esx_addons]/esx_dmvschool

  - action: remove_path
    path: ./resources/[esx_addons]/esx_drugs

  - action: remove_path
    path: ./resources/[esx_addons]/esx_garage

  - action: remove_path
    path: ./resources/[esx_addons]/esx_hud

  - action: remove_path
    path: ./resources/[esx_addons]/esx_joblisting

  - action: remove_path
    path: ./resources/[esx_addons]/esx_property

  - action: remove_path
    path: ./resources/[esx_addons]/esx_rpchat

  - action: remove_path
    path: ./resources/[esx_addons]/esx_shops

  - action: remove_path
    path: ./resources/[esx_addons]/esx_weaponshop

  - action: waste_time
    seconds: 10

  - action: query_database
    file: ./tmp/core/[SQL]/legacy.sql


## --- '####################' --- ##
## --- '### DEPENDANCIES ###' --- ##
## --- '####################' --- ##

  - action: download_github
    src: https://github.com/Byte-Labs-Studio/bl_bridge
    ref: main
    dest: ./resources/[dependants]/bl_bridge

  - action: download_github
    src: https://github.com/Xogy/xsound
    ref: master
    dest: ./resources/[dependants]/xsound

  - action: download_github
    src: https://github.com/DonStylz74/screenshot-basic
    ref: master
    dest: ./resources/[dependants]/screenshot-basic

  - action: download_github
    src: https://github.com/DonStylz74/VehicleDeformation
    ref: main
    dest: ./resources/[dependants]/VehicleDeformation

  - action: download_github
    src: https://github.com/stevoscriptsteam/stevo_lib
    ref: main
    dest: ./resources/[dependants]/stevo_lib

  - action: download_github
    src: https://github.com/DonStylz74/ultra-voltlab
    ref: main
    dest: ./resources/[dependants]/ultra-voltlab

  - action: download_github
    src: https://github.com/DonStylz74/SN-Hacking
    ref: main
    dest: ./resources/[dependants]/SN-Hacking

  - action: waste_time
    seconds: 5


## --- '###########################################' --- ##
## --- '## CUSTOM SCRIPT INJECTION & INSTALATION ##' --- ##
## --- '###########################################' --- ##

  - action: download_github
    src: https://github.com/DonStylz74/bob74_ipl
    ref: master
    dest: ./resources/[mapping]/bob74_ipl

  - action: download_github
    src: https://github.com/DonStylz74/loading_screen
    ref: main
    dest: ./resources/[core]/loading_screen


  - action: download_github
    src: https://github.com/DonStylz74/illenium-appearance
    ref: main
    dest: ./resources/[esx_addons]/illenium-appearance

  - action: download_github
    src: https://github.com/DonStylz74/LGF_PauseMenu
    ref: main
    dest: ./resources/[esx_addons]/LGF_PauseMenu

  - action: download_github
    src: https://github.com/DonStylz74/LGF_ChatV4
    ref: main
    dest: ./resources/[esx_addons]/LGF_ChatV4

  - action: download_github
    src: https://github.com/DonStylz74/randol_paycheck
    ref: main
    dest: ./resources/[esx_addons]/randol_paycheck

  - action: download_github
    src: https://github.com/DonStylz74/lunar_jobcentre
    ref: main
    dest: ./resources/[esx_addons]/lunar_jobcentre

  - action: download_github
    src: https://github.com/DonStylz74/CayoTwoIslands
    ref: main
    dest: ./resources/[esx_addons]/CayoTwoIslands

  - action: download_github
    src: https://github.com/DonStylz74/oulsen_satmap
    ref: main
    dest: ./tmp/oulsen_satmap

## -  Hash bellow to not install atlas postal maps - remove hashs on to install postal maps 
  ##- action: download_github
  #  src: https://github.com/DonStylz74/postal-map
  #  ref: main
  #  dest: ./resources/[esx_addons]/postal-map

## -  Hash bellow to not install atlas sat maps - remove hashs on to install sat maps 
  - action: copy_path
    src: ./tmp/oulsen_satmap/oulsen_satmap
    dest: ./resources/[esx_addons]/oulsen_satmap
    overwrite: true

  - action: download_github
    src: https://github.com/Hexora-Studios/esx_billing-redesign
    ref: main
    dest: ./tmp/addons/esx_billing

  - action: move_path
    src: ./tmp/addons/esx_billing
    dest: ./resources/[addons]/esx_billing
    overwrite: true

  - action: download_github
    src: https://github.com/DonStylz74/tcd-starterpack
    ref: main
    dest: ./resources/[esx_addons]/tcd-starterpack

  - action: download_github
    src: https://github.com/DonStylz74/wasabi_backpack
    ref: main
    dest: ./resources/[esx_addons]/wasabi_backpack

  - action: waste_time
    seconds: 5

  - action: download_github
    src: https://github.com/DonStylz74/lation_pawnshop
    ref: main
    dest: ./resources/[esx_extras]/lation_pawnshop

  - action: download_github
    src: https://github.com/DonStylz74/vehiclehandler
    ref: main
    dest: ./resources/[standalone]/vehiclehandler

  - action: download_github
    src: https://github.com/DonStylz74/ed_scuba
    ref: main
    dest: ./resources/[standalone]/ed_scuba

  - action: download_github
    src: https://github.com/DonStylz74/nv_sit_on_every_chair
    ref: v1.1
    dest: ./resources/[standalone]/nv_sit_on_every_chair

  - action: download_github
    src: https://github.com/DonStylz74/wn_atmrobbery
    ref: main
    dest: ./resources/[esx_extras]/[illegal]/wn_atmrobbery

  - action: download_github
    src: https://github.com/skeletonnetworks/SN-StoreRobbery
    ref: main
    dest: ./resources/[esx_extras]/[illegal]/SN-StoreRobbery

  - action: download_github
    src: https://github.com/DonStylz74/stevo_chopshop
    ref: main
    dest: ./resources/[esx_extras]/[illegal]/stevo_chopshop

  - action: download_github
    src: https://github.com/DonStylz74/stevo_portablemoneywash
    ref: main
    dest: ./resources/[esx_extras]/[illegal]/stevo_portablemoneywash

  - action: download_github
    src: https://github.com/DonStylz74/OT_pushvehicle
    ref: main
    dest: ./resources/[standalone]/OT_pushvehicle

  - action: download_github
    src: https://github.com/DonStylz74/it-drugs
    ref: main
    dest: ./resources/[esx_extras]/[illegal]/it-drugs

  - action: download_github
    src: https://github.com/DonStylz74/dss-cityguide
    ref: main
    dest: ./resources/[standalone]/dss-cityguide

  - action: download_github
    src: https://github.com/DonStylz74/dss_quikcrafting
    ref: main
    dest: ./resources/[standalone]/dss_quikcrafting

  - action: download_github
    src: https://github.com/DonStylz74/citra-taxi
    ref: main
    dest: ./resources/[standalone]/citra-taxi

  - action: download_github
    src: https://github.com/DonStylz74/fivem-aerial-tramway
    ref: master
    dest: ./resources/[standalone]/aerial-tramway-trains

  - action: download_github
    src: https://github.com/DonStylz74/ixhal-carwash
    ref: main
    dest: ./tmp/ixhal-carwash

  - action: waste_time
    seconds: 5

  - action: download_file
    url: https://github.com/Byte-Labs-Studio/bl_idcard/releases/download/v1.5.1/bl_idcard.zip
    path: ./tmp/bl_idcard.zip
  - action: unzip
    src: ./tmp/bl_idcard.zip
    dest: ./resources/[esx_addons]

  - action: download_file
    url: https://github.com/Maximus7474/5m-Elevator/releases/download/v1.2.4/5m-Elevator.zip
    path: ./tmp/5m-Elevator.zip
  - action: unzip
    src: ./tmp/5m-Elevator.zip
    dest: ./resources/[standalone]/5m-Elevator

  - action: download_file
    url: https://github.com/Renewed-Scripts/Renewed-Banking/releases/tag/v2.1.4/Renewed-Banking.zip
    path: ./tmp/Renewed-Banking.zip
  - action: unzip
    src: ./tmp/Renewed-Banking.zip
    dest: ./resources/[standalone]

  - action: download_github
    src: https://github.com/AvarianKnight/pma-voice
    ref: main
    dest: ./resources/[standalone]/pma-voice


## --- '#######################' --- ##
## --- '###  OX INSTALATION ###' --- ##
## --- '#######################' --- ##

  - action: download_file
    url: https://github.com/overextended/ox_lib/releases/latest/download/ox_lib.zip
    path: ./tmp/ox_lib.zip
  - action: unzip
    src: ./tmp/ox_lib.zip
    dest: ./resources/[ox]

  - action: download_github
    src: https://github.com/overextended/ox_target
    ref: main
    dest: ./resources/[ox]/ox_target

  - action: download_file
    url: https://github.com/overextended/oxmysql/releases/latest/download/oxmysql.zip
    path: ./tmp/oxmysql.zip
  - action: unzip
    src: ./tmp/oxmysql.zip
    dest: ./resources/[ox]

  - action: download_file
    url: https://github.com/overextended/ox_doorlock/releases/latest/download/ox_doorlock.zip
    path: ./tmp/ox_doorlock.zip
  - action: unzip
    src: ./tmp/ox_doorlock.zip
    dest: ./resources/[ox]

  - action: download_file
    url: https://github.com/overextended/ox_inventory/releases/latest/download/ox_inventory.zip
    path: ./tmp/ox_inventory.zip
  - action: unzip
    src: ./tmp/ox_inventory.zip
    dest: ./resources/[ox]

  - action: download_github
    src: https://github.com/overextended/ox_fuel
    ref: main
    dest: ./resources/[ox]/ox_fuel

  - action: waste_time
    seconds: 10

## --- '###############################################################' --- ##
## --- '### EXTRA SCRIPTS INSTALATION PROCESS - Tebex Purchases Etc ###' --- ##
## --- '###############################################################' --- ##

  - action: move_path
    src: ./recipe/Extras/ENT510_Multicharacter
    dest: ./resources/[esx_addons]/ENT510_Multicharacter
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/[license-schools]
    dest: ./resources/[esx_addons]/[license-schools]
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/it_bridge
    dest: ./resources/[dependants]/it_bridge
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/jg-scoreboard
    dest: ./resources/[esx_addons]/jg-scoreboard
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/0r-hud-v3
    dest: ./resources/[esx_addons]/0r-hud-v3
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/0r-towtruck
    dest: ./resources/[esx_extras]/0r-towtruck
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/flatbed3
    dest: ./resources/[vehicles]/flatbed3
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/solos-jointroll
    dest: ./resources/[esx_extras]/[illegal]/solos-jointroll
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/kq_lootareas
    dest: ./resources/[esx_extras]/[illegal]/kq_lootareas
    overwrite: true

  - action: move_path
    src: ./recipe/Extras/rm_chopshop
    dest: ./resources/[esx_extras]/[illegal]/rm_chopshop
    overwrite: true

  - action: move_path
    src: ./tmp/ixhal-carwash/ixhal-carwash
    dest: ./resources/[standalone]/ixhal-carwash
    overwrite: true

  - action: waste_time
    seconds: 10


## --- '###################################' --- ##
## --- '### SERVER MAPPING INSTALLATION ###' --- ##
## --- '###################################' --- ##

  - action: download_file
    url: https://github.com/GreenBerg21/mlo-dmv/releases/download/release-1.2/gc-dmv-1.2.zip
    path: ./tmp/gc-dmv-1.2.zip
  - action: unzip
    src: ./tmp/gc-dmv-1.2.zip
    dest: ./tmp/dmv

  - action: download_github
    src: https://github.com/PatocheMapping/paleto_gas_station/tree/main/patoche_gas_station
    ref: main
    dest: ./tmp/paleto_gas_station

  - action: download_file
    url: https://files.gta5-mods.com/uploads/car-dealer-fivem-sp-ready/fa9ab2-patoche_free_cardealer.zip
    path: ./tmp/fa9ab2-patoche_free_cardealer.zip
  - action: unzip
    src: ./tmp/fa9ab2-patoche_free_cardealer.zip
    dest: ./tmp/cardealer

  - action: download_file
    url: https://files.gta5-mods.com/uploads/mlo-secret-weapon-dealer-fivem-altv-sp-ready/e2c3b3-Patoche_weapon_dealer_fivem_altv_sp.zip
    path: ./tmp/Patoche_weapon_dealer.zip
  - action: unzip
    src: ./tmp/Patoche_weapon_dealer.zip
    dest: ./tmp/weapondealer

  - action: waste_time
    seconds: 3

  - action: move_path
    src: ./tmp/dmv/mlo-dmv-main
    dest: ./resources/[mapping]/[services]/driving-school
    overwrite: true

  - action: move_path
    src: ./tmp/paleto_gas_station/patoche_gas_station
    dest: ./resources/[mapping]/[shops]/paleto_gas_station
    overwrite: true

  - action: move_path
    src: ./tmp/cardealer/[FIVEM]/[MAP]/patoche_free_cardealer
    dest: ./resources/[mapping]/[auto-dealers]/pdm-cardealer-rockford
    overwrite: true

  - action: move_path
    src: ./tmp/weapondealer/[FIVEM]/patoche_dealer_weapon
    dest: ./resources/[mapping]/[illegal]/weapon-dealer
    overwrite: true

  - action: waste_time
    seconds: 3


## --- '########################################' --- ##
## --- '### DATABASE  EXTRAS SQL INSTALATION ###' --- ##
## --- '########################################' --- ##

  - action: query_database
    file: ./recipe/extra.sql

  - action: waste_time
    seconds: 2

  - action: query_database
    file: ./recipe/vehicles-472-total.sql

  - action: waste_time
    seconds: 2


## --- '####################################' --- ##
## --- '### UPDATING SCRIPT FILES UPDATE ###' --- ##
## --- '####################################' --- ##

  - action: copy_path
    src: ./recipe/replace/es_ext-adjustments.lua
    dest: ./resources/[core]/es_extended/shared/config/adjustments.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/es_ext-cfg-main.lua
    dest: ./resources/[core]/es_extended/shared/config//main.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/es_ext-paycheck.lua
    dest: ./resources/[core]/es_extended/server/modules/paycheck.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/oxinv-mod-itm-server.lua
    dest: ./resources/[ox]/ox_inventory/modules/items/server.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/oxinv-items.lua
    dest: ./resources/[ox]/ox_inventory/data/items.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/oxinv-weapons.lua
    dest: ./resources/[ox]/ox_inventory/data/weapons.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/oxinv-shops.lua
    dest: ./resources/[ox]/ox_inventory/data/shops.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/bl-idcard_config.lua
    dest: ./resources/[esx_addons]/bl_idcard/config.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/itbridge-config.lua
    dest: ./resources/[dependants]/it_bridge/config.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/snstorerob-config.lua
    dest: ./resources/[esx_extras]/[illegal]/SN-StoreRobbery/config.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/5m-Elevator.lua
    dest: ./resources/[standalone]/5m-Elevator/shared/elevators.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/emsjob-fxmanifest.lua
    dest: ./resources/[esx_addons]/esx_ambulancejob/fxmanifest.lua
    overwrite: true

  - action: copy_path
    src: ./recipe/replace/poljob-fxmanifest.lua
    dest: ./resources/[esx_addons]/esx_policejob/fxmanifest.lua
    overwrite: true

## --- '## INSTALL OX ITEM IMAGES TO INVENTORY ###' --- ##

  - action: copy_path
    src: ./recipe/Extras/images/
    dest: ./resources/[ox]/ox_inventory/web/images
    overwrite: true

  - action: waste_time
    seconds: 5


  ## FINAL BUILD CLEANUP
  ## - UnComment bellow to remove installer TEMP folder
  #- action: remove_path
  #  path: ./tmp

  #- action: remove_path
  #  path: ./recipe/replace





  ## BELOW ARE RECIPE ACTIONS AND REFRENCES

  #- action: move_path
  #  src: ./recipe/Extras/[mapping]
  #  dest: ./resources/[mapping]
  # overwrite: true

  #- action: copy_path
  #  src: ./recipe/replace/itdrugs/config.lua # -- IT Drugs v1.4.3
  #  dest: ./resources/[esx_extras]/[illegal]/it-drugs/shared/config.lua
  # overwrite: true

  #- action: remove_path
  #  path: ./tmp

  ##- action: download_github
  #  src: https://github.com/DonStylz74/esx_cityhall
  #  ref: main
  #  dest: ./resources/[esx_addons]/esx_cityhall

  #- action: download_file
  #  path: ./tmp/Patoche_weapon_dealer.zip
  #  url: https://files.gta5-mods.com/uploads/mlo-secret-weapon-dealer-fivem-altv-sp-ready/e2c3b3-Patoche_weapon_dealer_fivem_altv_sp.zip
  #- action: unzip
  #  dest: ./tmp/weapondealer
  #  src: ./tmp/Patoche_weapon_dealer.zip

    #- action: query_database
  #  file: ./recipe/Extras/sql-cleanup.sql

  #- action: waste_time # prevent github throttling
  #  seconds: 3





